### ISSUE TITLE
Bug: empty `eth_getCode` responses not cached

### ISSUE THREAD

**Issue by xJonathanLEI** [erpc/erpc#55]
Commit 2d8f5c806a005cd2aebe6e04e22e4299648e9edb excludes empty responses from being cached or served. Having an empty reseult for `eth_getCode` is completely valid and true for all EOA accounts. This change has resulted in a lot of cache misses.

**Comment by aramalipoor** [comment]
You're correct certain eth_getCode and eth_call results could be legitimately `0x`

The issue that commit was trying to solve is when on recent blocks the data is not yet available, so was safer to skip caching.

In your use-case are you providing explicit blockNumber or is it using 'latest' tag?

One idea could be to:
- Retry such empty responses when it's against recent data
- But cache it nevertheless if even after retries it's still empty 

The main goal is to avoid caching empty too early 🤔

**Comment by aramalipoor** [comment]
Depending on your use-case this update might be helpful: https://github.com/erpc/erpc/pull/56

**Comment by xJonathanLEI** [comment]
> In your use-case are you providing explicit blockNumber or is it using 'latest' tag?

Yes I specify a block. I understand that recent (i.e. non-finalized) responses are not cached. We actually dealt with something related in #45 so I'm a bit familiar with the mechanism.

> sometimes on recent blocks the data might not be available yet, therefore it's safer to skip caching

I don't quite understand. Isn't this already guarded against by the said "only cache finalized blocks" mechanism? Why do we have to bar empty responses here? Would be great if we have more context.

For now I'm just using a fork that partially reverts the change, so it's nothing urgent. I'm not upstreaming since I don't have the full context of that change in the first place. Thanks for the attention.

**Comment by aramalipoor** [comment]
> Isn't this already guarded against by the said "only cache finalized blocks" mechanism?

It is but not entirely, the edge-case of caching it wrongly is if upstream A says this block is finalized, but we received the data from upstream B which is behind. The way it is solved is track finalization + sync state "per-upstream" so that we can accurately decide if such data is finalized + came from a fully synced node.

> Yes I specify a block.

In that case #56 should help, as it's properly implementing "cache only if finalized + node is synced".

**Comment by aramalipoor** [comment]
Going to close this one, let me know if #56 is still not helpful for your use-case.

I thought of either assuming '0x' responses non-empty-ish or provide a directive flag to override this behavior based on use-case. Ideally we can do something that is simple on the user-side.

The main reason '0x' is considered emptyish is if you send a TX for upstream A that changes a state, and then you eth_call on upstream B which because is still not fully synced gives you 0x
