### ISSUE TITLE
Does it support websocket?

### ISSUE THREAD

**Issue by greyireland** [erpc/erpc#84]

**Comment by aramalipoor** [comment]
@greyireland at the moment only HTTP is developed and the main focus is to make core features (rate limiting, failover policies, optimal traffic routing, caching features etc) solid and complete, then to introduce Subscriptions (websocket, kafka, etc) with proper actual load-balancing towards upstreams (not just proxy only 1 upstream, because if it dies erpc must transparently switch to another one).

Here's a feature request you can follow for this: https://erpc.featurebase.app/p/support-ws-endpoints

In meantime if you have ideas and specific requirements (what exact you want use this? do you need more websocket connection to upstream, or from your clients to erpc? do you mainly want subscriptions of new logs/blocks, or you want websocket to avoid http-handshake overhead?) please do share, it'll help when implementing.

**Comment by fdmota** [comment]
+1

**Comment by aramalipoor** [comment]
Closing this for now to track in https://erpc.featurebase.app/p/support-ws-endpoints
